# ç½‘ç«™è®¾ç½®
baseURL = 'https://wvstu.me/'
languageCode = 'en-us'
title = 'WVSTU'
theme = 'PaperMod'

# è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡
hasCJKLanguage = true

enableInlineShortcodes = true #æ˜¯å¦å†…è”çŸ­ç 
enableEmoji = true            # æ˜¯å¦ä½¿ç”¨ Emoji è¡¨æƒ…
enableRobotsTXT = false       # æ˜¯å¦çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“

[minify]
disableXML = true
minifyOutput = true

[params]
[params.assets]
favicon = '/images/ico/favicon.ico'
favicon16x16 = '/images/ico/favicon-16x16.png'
favicon32x32 = '/images/ico/favicon-32x32.png'
apple_touch_icon = '/images/ico/apple-touch-icon.png'

[params.profileMode]
enabled = true
title = 'Hi there ğŸ‘‹'
subtitle = 'ğŸ”¨ Under construction'
imageUrl = '/images/ico/android-chrome-512x512.png'
imageTitle = 'Meow'
imageWidth = 150
imageHeight = 150

[menu]
[[menu.main]]
identifier = 'Archive'
name = 'Archive'
url = '/archives/'
weight = 10

[[menu.main]]
identifier = 'Tags'
name = 'Tags'
url = '/tags/'
weight = 20

[[menu.main]]
identifier = 'Search'
name = 'Search'
url = '/search/'
weight = 30

[outputs]
home = ['HTML', 'RSS', 'JSON']
