# ç½‘ç«™è®¾ç½®
baseURL = 'https://wvstu.me/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh-cn"
title = 'WVSTU'
theme = 'PaperMod'

# è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡
hasCJKLanguage = true

enableInlineShortcodes = true #æ˜¯å¦å†…è”çŸ­ç 
enableEmoji = true            # æ˜¯å¦ä½¿ç”¨ Emoji è¡¨æƒ…
enableRobotsTXT = false       # æ˜¯å¦çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“

[minify]
    disableXML = true
    minifyOutput = true

[params]
    [params.assets]
        favicon = '/images/logo/favicon.ico'
        favicon16x16 = '/images/logo/favicon-16x16.png'
        favicon32x32 = '/images/logo/favicon-32x32.png'
        apple_touch_icon = '/images/logo/apple-touch-icon.png'
    [params.homeInfoParams]
        title = 'å—¨ï¼Œä½ å¥½ ğŸ‘‹'
        content = 'æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç½‘ç«™ï¼Œè¿™é‡Œè®°å½•äº†æˆ‘åœ¨å­¦ä¹ å’Œå·¥ä½œä¸­çš„ä¸€äº›ç»éªŒå’Œå¿ƒå¾—ï¼Œæ¬¢è¿é˜…è¯»ã€‚'

# ä»¥ä¸‹å†…å®¹ç›®å‰åœç”¨
        # [params.profileMode]
        # enabled = true
        # title = 'Hi there ğŸ‘‹'
        # subtitle = 'ğŸ”¨ Under construction'
        # imageUrl = '/images/logo/android-chrome-512x512.png'
        # imageTitle = 'Meow'
        # imageWidth = 150
        # imageHeight = 150

# [menu]
# [[menu.main]]
# identifier = 'archive'
# name = 'Archive'
# url = '/archives/'
# weight = 10

# [[menu.main]]
# identifier = 'tags'
# name = 'Tags'
# url = '/tags/'
# weight = 20

# [[menu.main]]
# identifier = 'search'
# name = 'Search'
# url = '/search/'
# weight = 30

# [outputs]
# home = ['HTML', 'RSS', 'JSON']
